name: Node.js

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '12.14.0'

      # - name: Set up working directory
      #   run: mkdir -p /angular-video-player
      #   working-directory: /angular-video-player

      # - name: Copy package.json and package-lock.json
      #   run: cp /package*.json .

      - name: Install dependencies
        run: npm install

      # - name: Copy all files
      #   run: cp -r ../* .

      # - name: Expose port 4200
      #   run: echo "EXPOSE 4200" >> Dockerfile  # Assuming this is intended for a Dockerfile

      # - name: Start the application
      #   run: npm start

      - name: Build the application
        run: npm run build